[build]
publish = "dist/"
command = "pnpm run spell && NODE_ENV=production pnpm run build"
ignore = "git diff --name-only $CACHED_COMMIT_REF $COMMIT_REF | tr -d '\n' | grep -Eq '^(README.md|LICENSE)$'"

[[plugins]]
    package = "netlify-plugin-11ty"
    [plugins.inputs]
        cache_img = 'assets/images/'
        cache_img_httpHeader = false
        cache_assets = false
        cache_other = []