name: Spell-check

on:
  pull_request:
    paths:
      - "**.md"
  push:
    paths:
      - "**.md"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: "**/*.md"
          verbose: true
